---
restic_excludes:
  - '.cache'
  - '.local/share/Trash'
  - 'Downloads'
  - 'mnt'
  - '.steam'
  - '.var'
  - 'node_modules'
  - '__pycache__'
  - '.venv'
  - 'target/'

restic_keep_daily: 7
restic_keep_weekly: 4
restic_keep_monthly: 6
