---
# Main laptop setup playbook
# Run with: ansible-playbook setup.yml --ask-become-pass

- name: Configure laptop
  hosts: localhost
  connection: local

  vars:
    user: "{{ ansible_user_id }}"
    home: "{{ ansible_env.HOME }}"
    workstation_dir: "{{ home }}/Repos/workstation"

  roles:
    - packages
    - dotfiles
    - restic
    - wallpaper
