---
# CLI tools
cli_packages:
  - git
  - vim
  - tmux
  - htop
  - curl
  - wget
  - unzip
  - tar
  - rsync
  - tree
  - jq
  - yq

utility_packages:
  - ripgrep
  - fzf

# Desktop/GUI apps
desktop_packages:
  - gnome-tweaks
  - gnome-extensions-app
  - firefox
  - libreoffice
  - virt-manager

# Development tools
dev_packages:
  - gcc
  - make
  - ansible
  - ansible-lint
  - ShellCheck

python_packages:
  - python3
  - python3-pip
  - python3-virtualenv
  - python3-devel

container_packages:
  - podman
  - podman-compose

# Flatpak apps
flatpak_apps:
  - net.cozic.joplin_desktop
  # - com.spotify.Client
  # - com.discordapp.Discord
